//@ts-ignore
import {v4 as uuid} from "uuid"

export const errorMessageResolver = (
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  error: any,
  defaultMessage?: string
): string => {
  return (
      error?.response?.data?.message ||
      error?.response?.message ||
      defaultMessage
  )
}

export const packageDemo = [
  {
    no: 1,id: uuid(),
     packageType: "10 diamonds",
    packageAmount: "1000ks",
  },
  {
    no: 2,id: uuid(),
     packageType: "10 diamonds",
    packageAmount: "1000ks",
  },
  {
    no: 3,id: uuid(),
     packageType: "10 diamonds",
    packageAmount: "1000ks",
  },
  {
    no: 4,id: uuid(),
     packageType: "10 diamonds",
    packageAmount: "1000ks",
  },
  {
    no: 5,id: uuid(),
     packageType: "10 diamonds",
    packageAmount: "1000ks",
  },
  {
    no: 6,id: uuid(),
     packageType: "10 diamonds",
    packageAmount: "1000ks",
  },
  {
    no: 7,id: uuid(),
     packageType: "10 diamonds",
    packageAmount: "1000ks",
  },
  {
    no: 8,id: uuid(),
     packageType: "10 diamonds",
    packageAmount: "1000ks",
  },

]

export const adminListUser = [
  {
    no: 1,id: uuid(),
    name: "spider man",
    role: "super admin",
  },
  {
    no: 2,id: uuid(),
    name: "Bat man",
    role: "main admin",
  },
  {
    no: 3,id: uuid(),
    name: " super man",
    role: "supervisor",
  },
  {
    no: 4,id: uuid(),
    name: "spider man",
    role: "super admin",
  },
  {
    no: 5,id: uuid(),
    name: "Bat man",
    role: "main admin",
  },
  {
    no: 6,id: uuid(),
    name: " super man",
    role: "supervisor",
  },
  {
    no: 7,id: uuid(),
    name: "spider man",
    role: "super admin",
  },
  {
    no: 8,id: uuid(),
    name: "Bat man",
    role: "main admin",
  },
  {
    no: 9,id: uuid(),
    name: " super man",
    role: "supervisor",
  },
  { id: uuid(),
    no: 10,
    
    name: "spider man",
    role: "super admin",
  },
  { id: uuid(),
    no: 11,
    
    name: "Bat man",
    role: "main admin",
  },
  { id: uuid(),
    no: 12,
    
    name: " super man",
    role: "supervisor",
  },
];

export const DailyList = [
  {
    no: 1,
    Date: "20240123",
    name: "Mg Mg",
    connected_merchant: "Food MM",
    package: "10 Diamonds",
    amount: "8000MMK",
    transaction_fee: "400MMK (5%)",
    total: "8400MMK",
    paymentMethod: "KBZ",
    paymentStatus: "Success",
    action: "",
  },

  {
    no: 2,
    Date: "20240123",
    name: "Mg Mg",
    connected_merchant: "Food MM",
    package: "10 Diamonds",
    amount: "8000MMK",
    transaction_fee: "400MMK (5%)",
    total: "8400MMK",
    paymentMethod: "KBZ",
    paymentStatus: "Success",
    action: "",
  },
  {
    no: 3,
    Date: "20240123",
    name: "Mg Mg",
    connected_merchant: "Food MM",
    package: "10 Diamonds",
    amount: "8000MMK",
    transaction_fee: "400MMK (5%)",
    total: "8400MMK",
    paymentMethod: "KBZ",
    paymentStatus: "Success",
    action: "",
  },
  {
    no: 4,
    Date: "20240123",
    name: "Mg Mg",
    connected_merchant: "Food MM",
    package: "10 Diamonds",
    amount: "8000MMK",
    transaction_fee: "400MMK (5%)",
    total: "8400MMK",
    paymentMethod: "KBZ",
    paymentStatus: "Success",
    action: "",
  },
  {
    no: 5,
    Date: "20240123",
    name: "Mg Mg",
    connected_merchant: "Food MM",
    package: "10 Diamonds",
    amount: "8000MMK",
    transaction_fee: "400MMK (5%)",
    total: "8400MMK",
    paymentMethod: "KBZ",
    paymentStatus: "Success",
    action: "",
  },
  {
    no: 6,
    Date: "20240123",
    name: "Mg Mg",
    connected_merchant: "Food MM",
    package: "10 Diamonds",
    amount: "8000MMK",
    transaction_fee: "400MMK (5%)",
    total: "8400MMK",
    paymentMethod: "KBZ",
    paymentStatus: "Success",
    action: "",
  },
  {
    no: 7,
    Date: "20240123",
    name: "Mg Mg",
    connected_merchant: "Food MM",
    package: "10 Diamonds",
    amount: "8000MMK",
    transaction_fee: "400MMK (5%)",
    total: "8400MMK",
    paymentMethod: "KBZ",
    paymentStatus: "Success",
    action: "",
  },

  {
    no: 8,
    Date: "20240123",
    name: "Mg Mg",
    connected_merchant: "Food MM",
    package: "10 Diamonds",
    amount: "8000MMK",
    transaction_fee: "400MMK (5%)",
    total: "8400MMK",
    paymentMethod: "KBZ",
    paymentStatus: "Success",
    action: "",
  },
  {
    no: 9,
    Date: "20240123",
    name: "Mg Mg",
    connected_merchant: "Food MM",
    package: "10 Diamonds",
    amount: "8000MMK",
    transaction_fee: "400MMK (5%)",
    total: "8400MMK",
    paymentMethod: "KBZ",
    paymentStatus: "Success",
    action: "",
  },
  {
    no: 10,
    Date: "20240123",
    name: "Mg Mg",
    connected_merchant: "Food MM",
    package: "10 Diamonds",
    amount: "8000MMK",
    transaction_fee: "400MMK (5%)",
    total: "8400MMK",
    paymentMethod: "KBZ",
    paymentStatus: "Success",
    action: "",
  },
  {
    no: 11,
    Date: "20240123",
    name: "Mg Mg",
    connected_merchant: "Food MM",
    package: "10 Diamonds",
    amount: "8000MMK",
    transaction_fee: "400MMK (5%)",
    total: "8400MMK",
    paymentMethod: "KBZ",
    paymentStatus: "Success",
    action: "",
  },
  {
    no: 12,
    Date: "20240123",
    name: "Mg Mg",
    connected_merchant: "Food MM",
    package: "10 Diamonds",
    amount: "8000MMK",
    transaction_fee: "400MMK (5%)",
    total: "8400MMK",
    paymentMethod: "KBZ",
    paymentStatus: "Success",
    action: "",
  },
  {
    no: 13,
    Date: "20240123",
    name: "Mg Mg",
    connected_merchant: "Food MM",
    package: "10 Diamonds",
    amount: "8000MMK",
    transaction_fee: "400MMK (5%)",
    total: "8400MMK",
    paymentMethod: "KBZ",
    paymentStatus: "Success",
    action: "",
  },
  {
    no: 14,
    Date: "20240123",
    name: "Mg Mg",
    connected_merchant: "Food MM",
    package: "10 Diamonds",
    amount: "8000MMK",
    transaction_fee: "400MMK (5%)",
    total: "8400MMK",
    paymentMethod: "KBZ",
    paymentStatus: "Success",
    action: "",
  },
  {
    no: 15,
    Date: "20240123",
    name: "Mg Mg",
    connected_merchant: "Food MM",
    package: "10 Diamonds",
    amount: "8000MMK",
    transaction_fee: "400MMK (5%)",
    total: "8400MMK",
    paymentMethod: "KBZ",
    paymentStatus: "Success",
    action: "",
  },
];
export const merchant = [
  {
    no: "1",
    merchantId: "123456",
    merchantName: "FoodMM",
    CompanyName: "Food MM",
    image: "",
    userCount: "5",
  },
  {
    no: "2",
    merchantId: "123456",
    merchantName: "FoodMM",
    CompanyName: "Food MM",
    image: "",
    userCount: "5",
  },
  {
    no: "3",
    merchantId: "123456",
    merchantName: "FoodMM",
    CompanyName: "Food MM",
    image: "",
    userCount: "5",
  },
  {
    no: "4",
    merchantId: "123456",
    merchantName: "FoodMM",
    CompanyName: "Food MM",
    image: "",
    userCount: "5",
  },
  {
    no: "5",
    merchantId: "123456",
    merchantName: "FoodMM",
    CompanyName: "Food MM",
    image: "",
    userCount: "5",
  },
  {
    no: "6",
    merchantId: "123456",
    merchantName: "FoodMM",
    CompanyName: "Food MM",
    image: "",
    userCount: "5",
  },
  {
    no: "7",
    merchantId: "123456",
    merchantName: "FoodMM",
    CompanyName: "Food MM",
    image: "",
    userCount: "5",
  },
  {
    no: "8",
    merchantId: "123456",
    merchantName: "FoodMM",
    CompanyName: "Food MM",
    image: "",
    userCount: "5",
  },
  {
    no: "9",
    merchantId: "123456",
    merchantName: "FoodMM",
    CompanyName: "Food MM",
    image: "",
    userCount: "5",
  },
  {
    no: "10",
    merchantId: "123456",
    merchantName: "FoodMM",
    CompanyName: "Food MM",
    image: "",
    userCount: "5",
  },
  {
    no: "11",
    merchantId: "123456",
    merchantName: "FoodMM",
    CompanyName: "Food MM",
    image: "",
    userCount: "5",
  },
  {
    no: "12",
    merchantId: "123456",
    merchantName: "FoodMM",
    CompanyName: "Food MM",
    image: "",
    userCount: "5",
  },
  {
    no: "13",
    merchantId: "123456",
    merchantName: "FoodMM",
    CompanyName: "Food MM",
    image: "",
    userCount: "5",
  },
  {
    no: "14",
    merchantId: "123456",
    merchantName: "FoodMM",
    CompanyName: "Food MM",
    image: "",
    userCount: "5",
  },
  {
    no: "15",
    merchantId: "123456",
    merchantName: "FoodMM",
    CompanyName: "Food MM",
    image: "",
    userCount: "5",
  },
  {
    no: "16",
    merchantId: "123456",
    merchantName: "FoodMM",
    CompanyName: "Food MM",
    image: "",
    userCount: "5",
  },
  {
    no: "17",
    merchantId: "123456",
    merchantName: "FoodMM",
    CompanyName: "Food MM",
    image: "",
    userCount: "5",
  },
  {
    no: "18",
    merchantId: "123456",
    merchantName: "FoodMM",
    CompanyName: "Food MM",
    image: "",
    userCount: "5",
  },
  {
    no: "19",
    merchantId: "123456",
    merchantName: "FoodMM",
    CompanyName: "Food MM",
    image: "",
    userCount: "5",
  },
  {
    no: "20",
    merchantId: "123456",
    merchantName: "FoodMM",
    CompanyName: "Food MM",
    image: "",
    userCount: "5",
  },
  {
    no: "21",
    merchantId: "123456",
    merchantName: "FoodMM",
    CompanyName: "Food MM",
    image: "",
    userCount: "5",
  },
  {
    no: "22",
    merchantId: "123456",
    merchantName: "FoodMM",
    CompanyName: "Food MM",
    image: "",
    userCount: "5",
  },
  {
    no: "23",
    merchantId: "123456",
    merchantName: "FoodMM",
    CompanyName: "Food MM",
    image: "",
    userCount: "5",
  },
];
export const user = [
  {
    no: 1,
    name: "aung kyaw khaing",
    email: "aungkyawkhaing2000@gmail.com",
    password: "some",
    profile: "something",
  },
  {
    no: 2,
    name: "hayabusa",
    email: "aungkyawkhaing2000@gmail.com",
    password: "some",
    profile: "something",
  },
  {
    no: 3,
    name: "knowledge",
    email: "aungkyawkhaing2000@gmail.com",
    password: "some",
    profile: "something",
  },
  {
    no: 4,
    name: "natalia",
    email: "aungkyawkhaing2000@gmail.com",
    password: "some",
    profile: "something",
  },
  {
    no: 5,
    name: "aung kyaw khaing",
    email: "aungkyawkhaing2000@gmail.com",
    password: "some",
    profile: "something",
  },
  {
    no: 6,
    name: "hayabusa",
    email: "aungkyawkhaing2000@gmail.com",
    password: "some",
    profile: "something",
  },
  {
    no: 7,
    name: "knowledge",
    email: "aungkyawkhaing2000@gmail.com",
    password: "some",
    profile: "something",
  },
  {
    no: 8,
    name: "natalia",
    email: "aungkyawkhaing2000@gmail.com",
    password: "some",
    profile: "something",
  },
  {
    no: 9,
    name: "aung kyaw khaing",
    email: "aungkyawkhaing2000@gmail.com",
    password: "some",
    profile: "something",
  },
  {
    no: 10,
    name: "hayabusa",
    email: "aungkyawkhaing2000@gmail.com",
    password: "some",
    profile: "something",
  },
  {
    no: 11,
    name: "knowledge",
    email: "aungkyawkhaing2000@gmail.com",
    password: "some",
    profile: "something",
  },
  {
    no: 12,
    name: "natalia",
    email: "aungkyawkhaing2000@gmail.com",
    password: "some",
    profile: "something",
  },
  {
    no: 13,
    name: "aung kyaw khaing",
    email: "aungkyawkhaing2000@gmail.com",
    password: "some",
    profile: "something",
  },
  {
    no: 14,
    name: "hayabusa",
    email: "aungkyawkhaing2000@gmail.com",
    password: "some",
    profile: "something",
  },
  {
    no: 15,
    name: "knowledge",
    email: "aungkyawkhaing2000@gmail.com",
    password: "some",
    profile: "something",
  },
  {
    no: 16,
    name: "natalia",
    email: "aungkyawkhaing2000@gmail.com",
    password: "some",
    profile: "something",
  },
  {
    no: 17,
    name: "aung kyaw khaing",
    email: "aungkyawkhaing2000@gmail.com",
    password: "some",
    profile: "something",
  },
  {
    no: 18,
    name: "hayabusa",
    email: "aungkyawkhaing2000@gmail.com",
    password: "some",
    profile: "something",
  },
  {
    no: 19,
    name: "knowledge",
    email: "aungkyawkhaing2000@gmail.com",
    password: "some",
    profile: "something",
  },
  {
    no: 20,
    name: "natalia",
    email: "aungkyawkhaing2000@gmail.com",
    password: "some",
    profile: "something",
  },
  {
    no: 21,
    name: "aung kyaw khaing",
    email: "aungkyawkhaing2000@gmail.com",
    password: "some",
    profile: "something",
  },
  {
    no: 22,
    name: "hayabusa",
    email: "aungkyawkhaing2000@gmail.com",
    password: "some",
    profile: "something",
  },
  {
    no: 23,
    name: "knowledge",
    email: "aungkyawkhaing2000@gmail.com",
    password: "some",
    profile: "something",
  },
  {
    no: 24,
    name: "natalia",
    email: "aungkyawkhaing2000@gmail.com",
    password: "some",
    profile: "something",
  },
  {
    no: 25,
    name: "aung kyaw khaing",
    email: "aungkyawkhaing2000@gmail.com",
    password: "some",
    profile: "something",
  },
  {
    no: 26,
    name: "hayabusa",
    email: "aungkyawkhaing2000@gmail.com",
    password: "some",
    profile: "something",
  },
  {
    no: 27,
    name: "knowledge",
    email: "aungkyawkhaing2000@gmail.com",
    password: "some",
    profile: "something",
  },
  {
    no: 28,
    name: "natalia",
    email: "aungkyawkhaing2000@gmail.com",
    password: "some",
    profile: "something",
  },
  {
    no: 29,
    name: "aung kyaw khaing",
    email: "aungkyawkhaing2000@gmail.com",
    password: "some",
    profile: "something",
  },
  {
    no: 30,
    name: "hayabusa",
    email: "aungkyawkhaing2000@gmail.com",
    password: "some",
    profile: "something",
  },
  {
    no: 31,
    name: "knowledge",
    email: "aungkyawkhaing2000@gmail.com",
    password: "some",
    profile: "something",
  },
  {
    no: 32,
    name: "natalia",
    email: "aungkyawkhaing2000@gmail.com",
    password: "some",
    profile: "something",
  },
  {
    no: 33,
    name: "aung kyaw khaing",
    email: "aungkyawkhaing2000@gmail.com",
    password: "some",
    profile: "something",
  },
  {
    no: 34,
    name: "hayabusa",
    email: "aungkyawkhaing2000@gmail.com",
    password: "some",
    profile: "something",
  },
  {
    no: 35,
    name: "knowledge",
    email: "aungkyawkhaing2000@gmail.com",
    password: "some",
    profile: "something",
  },
  {
    no: 36,
    name: "natalia",
    email: "aungkyawkhaing2000@gmail.com",
    password: "some",
    profile: "something",
  },
  {
    no: 37,
    name: "aung kyaw khaing",
    email: "aungkyawkhaing2000@gmail.com",
    password: "some",
    profile: "something",
  },
];
